# Default config
tabWidth: 4
endOfLine: lf
singleQuote: false
printWidth: 80
trailingComma: none
bracketSameLine: true
quoteProps: consistent
experimentalTernaries: true

# Overrided config
overrides:
  - files: ["*.md", "*.json", "*.yaml"]
    options:
      tabWidth: 2
      singleQuote: false
  - files: ["*.scss"]
    options:
      singleQuote: false
